import os
import psycopg2
from psycopg2.extras import RealDictCursor


DATABASE_URL = os.environ.get("DATABASE_URL")


def get_db():
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL environment variable is not set.")

    return psycopg2.connect(
        DATABASE_URL,
        sslmode="require"
    )


def create_table():
    conn = get_db()

    with conn.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS series (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                genre TEXT,
                status TEXT NOT NULL,
                rating REAL DEFAULT 0,
                episodes INTEGER DEFAULT 0,
                total_episodes INTEGER DEFAULT 0
            )
        """)

    conn.commit()
    conn.close()